<a href="https://colab.research.google.com/github/Mandar-Ghatekar/IEX-Electricity-Market-Analysis/blob/main/IEX_Electicity_Market_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd

df = pd.read_excel('DAM_Market Snapshot.xlsx')

print(f"Total rows (Time Blocks): {df.shape[0]}")
print(f"Total data columns: {df.shape[1]}")

display(df.head(20))

Total rows (Time Blocks): 105
Total data columns: 8

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Market Snapshot,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Date: 15-06-2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Date,Hour,Time Block,Purchase Bid (MW),Sell Bid (MW),MCV (MW),Final Scheduled Volume (MW),MCP (Rs/MWh) *
4,15-06-2026,1,00:00 - 00:15,13866.10,8305.30,6036.00,6036.00,5499.53
5,15-06-2026,1,00:15 - 00:30,13674.90,8648.40,5972.50,5972.50,5450.63
6,15-06-2026,1,00:30 - 00:45,13469.40,8898.80,5883.09,5883.09,4872.41
7,15-06-2026,1,00:45 - 01:00,13737.70,9245.80,6573.20,6573.20,5000.10
8,15-06-2026,2,01:00 - 01:15,13765.40,9660.50,6806.50,6806.50,5000.02
9,15-06-2026,2,01:15 - 01:30,12961.50,9718.60,6751.50,6751.50,4999.19
10,15-06-2026,2,01:30 - 01:45,12502.40,9822.20,6399.00,6399.00,4576.33
11,15-06-2026,2,01:45 - 02:00,11909.40,10386.30,6263.00,6263.00,4449.65
12,15-06-2026,3,02:00 - 02:15,11252.30,11142.80,5915.80,5915.80,4295.07
13,15-06-2026,3,02:15 - 02:30,11202.30,11373.50,5946.60,5946.60,4002.74
14,15-06-2026,3,02:30 - 02:45,11156.80,11942.90,6080.00,6080.00,3959.66
15,15-06-2026,3,02:45 - 03:00,10891.90,12288.60,5990.80,5990.80,3724.21
16,15-06-2026,4,03:00 - 03:15,10785.90,13037.30,5924.90,5924.90,3688.84
17,15-06-2026,4,03:15 - 03:30,10705.40,13173.00,5907.60,5907.60,3644.49
18,15-06-2026,4,03:30 - 03:45,10707.60,13362.30,5993.20,5993.20,3612.92
19,15-06-2026,4,03:45 - 04:00,10601.40,13980.10,5890.00,5890.00,3612.53

In [17]:
df1 = pd.read_excel('DAM_Market Snapshot.xlsx',skiprows=3)
display(df1.head(20))

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Date,Hour,Time Block,Purchase Bid (MW),Sell Bid (MW),MCV (MW),Final Scheduled Volume (MW),MCP (Rs/MWh) *
1,15-06-2026,1,00:00 - 00:15,13866.10,8305.30,6036.00,6036.00,5499.53
2,15-06-2026,1,00:15 - 00:30,13674.90,8648.40,5972.50,5972.50,5450.63
3,15-06-2026,1,00:30 - 00:45,13469.40,8898.80,5883.09,5883.09,4872.41
4,15-06-2026,1,00:45 - 01:00,13737.70,9245.80,6573.20,6573.20,5000.10
5,15-06-2026,2,01:00 - 01:15,13765.40,9660.50,6806.50,6806.50,5000.02
6,15-06-2026,2,01:15 - 01:30,12961.50,9718.60,6751.50,6751.50,4999.19
7,15-06-2026,2,01:30 - 01:45,12502.40,9822.20,6399.00,6399.00,4576.33
8,15-06-2026,2,01:45 - 02:00,11909.40,10386.30,6263.00,6263.00,4449.65
9,15-06-2026,3,02:00 - 02:15,11252.30,11142.80,5915.80,5915.80,4295.07
10,15-06-2026,3,02:15 - 02:30,11202.30,11373.50,5946.60,5946.60,4002.74
11,15-06-2026,3,02:30 - 02:45,11156.80,11942.90,6080.00,6080.00,3959.66
12,15-06-2026,3,02:45 - 03:00,10891.90,12288.60,5990.80,5990.80,3724.21
13,15-06-2026,4,03:00 - 03:15,10785.90,13037.30,5924.90,5924.90,3688.84
14,15-06-2026,4,03:15 - 03:30,10705.40,13173.00,5907.60,5907.60,3644.49
15,15-06-2026,4,03:30 - 03:45,10707.60,13362.30,5993.20,5993.20,3612.92
16,15-06-2026,4,03:45 - 04:00,10601.40,13980.10,5890.00,5890.00,3612.53
17,15-06-2026,5,04:00 - 04:15,10603.60,14239.60,5953.00,5953.00,3612.42
18,15-06-2026,5,04:15 - 04:30,10607.90,14641.60,5957.60,5957.60,3612.31
19,15-06-2026,5,04:30 - 04:45,10506.00,14666.20,5858.90,5858.90,3612.17